{{-- Global Media Picker Modal - Bootstrap 5 (Modern) --}}
<x-admin.modal id="global-media-picker" title="Thư viện Media" maxWidth="modal-fullscreen modal-dialog-scrollable">
    <div class="picker-body d-flex flex-column">
        <ul class="nav picker-tabs shrink-0" role="tablist">
            <li class="nav-item"><button type="button" id="picker-tab-browse" role="tab" aria-selected="true" aria-controls="picker-panel-browse" class="nav-link active">Thư viện</button></li>
            <li class="nav-item"><button type="button" id="picker-tab-upload" role="tab" aria-selected="false" aria-controls="picker-panel-upload" class="nav-link">Tải lên</button></li>
        </ul>
        <div id="picker-panel-browse" class="flex-grow-1 d-flex flex-column" style="min-height:0;" role="tabpanel" aria-labelledby="picker-tab-browse">
            <div class="picker-toolbar d-flex flex-wrap align-items-center gap-2 shrink-0">
                {{-- Nút back: chỉ hiện khi đang ở trong thư mục --}}
                <button type="button" id="picker-btn-back" class="btn btn-outline-secondary btn-sm d-none shrink-0" title="Quay lại">
                    <svg width="15" height="15" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
                    <span class="ms-1 small">Quay lại</span>
                </button>
                <div class="picker-search-wrap position-relative flex-grow-1">
                    <input type="text" id="picker-search" placeholder="Tìm kiếm file..." class="form-control form-control-sm">
                    <svg width="15" height="15" class="picker-search-icon position-absolute top-50 translate-middle-y" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>
                </div>
                <select id="picker-filter-type" class="form-select form-select-sm w-auto picker-filter-select"><option value="">Tất cả</option><option value="image" selected>Hình ảnh</option><option value="document">Tài liệu</option><option value="video">Video</option></select>
                <select id="picker-filter-sort" class="form-select form-select-sm w-auto picker-filter-select"><option value="desc" selected>Mới nhất</option><option value="asc">Cũ nhất</option></select>
                <div class="picker-view-toggle btn-group btn-group-sm ms-auto shrink-0">
                    <button type="button" id="picker-view-grid" class="btn btn-outline-secondary active" title="Lưới"><svg width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"/></svg></button>
                    <button type="button" id="picker-view-list" class="btn btn-outline-secondary" title="Danh sách"><svg width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/></svg></button>
                </div>
                <button type="button" id="picker-btn-refresh" class="btn btn-outline-secondary btn-sm" title="Làm mới"><svg width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg></button>
            </div>
            <div class="d-flex flex-grow-1 picker-content-area" style="min-height:0; overflow:hidden;">
                <div class="d-flex flex-column flex-grow-1 picker-main-col" style="min-height:0; overflow:hidden;">
                    <div id="picker-folder-section" class="shrink-0 d-none"><nav id="picker-folder-breadcrumb" class="small text-body-secondary mb-2"></nav><div id="picker-folder-grid" class="row g-2 mb-2"></div></div>
                    <div id="picker-grid-container" class="flex-grow-1 custom-scrollbar position-relative" style="min-height:0; overflow:hidden auto;">
                        <div id="picker-loading-indicator" class="text-center py-4 d-none"><div class="spinner-border spinner-border-sm text-primary" role="status"></div><span class="ms-2 small text-body-secondary">Đang tải...</span></div>
                        <div id="picker-grid" class="row g-2"></div>
                        <div id="picker-load-more-trigger" class="text-center py-3 d-none"><button type="button" id="picker-btn-load-more" class="btn btn-sm btn-outline-secondary">Tải thêm...</button></div>
                        <div id="picker-grid-drop-overlay" class="picker-grid-drop-overlay position-absolute top-0 start-0 w-100 h-100 d-none flex-column align-items-center justify-content-center"><svg width="48" height="48" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="text-primary"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"/></svg><span class="small text-primary fw-semibold mt-2">Thả file để tải lên</span></div>
                    </div>
                </div>{{-- /.picker-main-col --}}
                <div class="d-flex flex-column picker-sidebar shrink-0" style="min-height:0; width:260px; overflow:hidden;">
                    <div id="sidebar-content-state" class="d-flex flex-column row-gap-2 h-100 overflow-y-auto custom-scrollbar p-3 d-none">
                        <div><div id="sidebar-preview-box" class="picker-sidebar-preview d-flex align-items-center justify-content-center position-relative"><img id="sidebar-preview-img" src="" class="w-100 h-100 object-fit-cover d-none" alt=""><div id="sidebar-preview-icon" class="text-body-secondary"><svg width="48" height="48" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg></div></div></div>
                        <div class="picker-sidebar-info mt-2">
                            <span class="info-label">Tên file</span><span id="sidebar-info-name" class="info-value text-truncate"></span>
                            <span class="info-label">Ngày tải</span><span id="sidebar-info-date" class="info-value"></span>
                            <span class="info-label">Kích thước</span><span id="sidebar-info-size" class="info-value"></span>
                            <span class="info-label">Loại</span><span id="sidebar-info-mime" class="info-value"></span>
                        </div>
                        <div class="mt-auto pt-2"><input id="sidebar-info-url" type="text" class="picker-sidebar-url form-control form-control-sm w-100" readonly onclick="this.select()"></div>
                        <button type="button" id="sidebar-btn-delete" class="btn btn-outline-danger btn-sm w-100 d-flex align-items-center justify-content-center gap-1 mt-1"><svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>Xóa vĩnh viễn</button>
                    </div>
                    <div id="sidebar-empty-state" class="picker-sidebar-empty d-flex align-items-center justify-content-center h-100 small text-center p-3"><span>Chọn một file để xem thông tin chi tiết</span></div>
                </div>
            </div>
            <div class="picker-footer d-flex align-items-center justify-content-between shrink-0">
                <div class="small fw-medium text-body-secondary" id="picker-meta-info"></div>
                <div class="d-flex gap-2"><x-admin.button type="button" variant="secondary" onclick="closeModal('global-media-picker')">Hủy</x-admin.button><x-admin.button type="button" variant="primary" id="picker-btn-confirm" disabled>Xác nhận chọn</x-admin.button></div>
            </div>
        </div>
        <div id="picker-panel-upload" class="d-none flex-grow-1 d-flex flex-column" style="min-height:0;" role="tabpanel" aria-labelledby="picker-tab-upload">
            <div id="picker-dropzone" class="picker-dropzone flex-grow-1 position-relative d-flex flex-column align-items-center justify-content-center gap-3 p-5 text-center">
                <input type="file" id="picker-file-input" accept="image/jpeg,image/png,image/webp,image/gif,image/svg+xml,application/pdf,video/mp4,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv,application/zip,application/x-rar-compressed,text/plain" class="position-absolute top-0 start-0 w-100 h-100 opacity-0" style="cursor:pointer;z-index:10;">
                <div class="picker-dropzone-icon d-flex align-items-center justify-content-center mb-2"><svg width="32" height="32" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"/></svg></div>
                <div><p class="fw-bold fs-5 mb-1">Kéo thả file vào đây</p><p class="small text-body-secondary mb-1">hoặc <span class="text-primary text-decoration-underline">bấm để chọn từ máy tính</span></p><p class="small text-body-tertiary mb-0">Tối đa 10MB</p></div>
                <div id="picker-upload-overlay" class="picker-upload-overlay position-absolute top-0 start-0 w-100 h-100 d-none flex-column align-items-center justify-content-center">
                    <div class="picker-progress-card"><div class="d-flex justify-content-between small fw-bold mb-2"><span id="picker-progress-name" class="text-truncate pe-3">Đang tải lên...</span><span id="picker-progress-pct" class="text-primary">0%</span></div><div class="progress"><div id="picker-progress-bar" class="progress-bar" role="progressbar" style="width:0%"></div></div></div>
                </div>
            </div>
            <div id="picker-upload-result" class="picker-upload-result d-none mt-3 d-flex align-items-center gap-3 shrink-0 p-3">
                <img id="picker-upload-thumb" src="" class="object-fit-cover rounded border d-none" style="width:3.5rem;height:3.5rem;" alt="">
                <div class="flex-grow-1" style="min-width:0"><p class="small fw-bold text-success mb-0">✅ Tải lên thành công!</p><p id="picker-upload-filename" class="small text-body-secondary mt-1 text-truncate mb-0"></p></div>
                <button type="button" id="picker-btn-use-uploaded" class="btn btn-success btn-sm fw-bold shrink-0">Sử dụng ảnh này</button>
            </div>
        </div>
    </div>
</x-admin.modal>

@pushOnce('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    var modal=document.getElementById('global-media-picker');if(!modal)return;
    var tabBrowse=document.getElementById('picker-tab-browse'),tabUpload=document.getElementById('picker-tab-upload');
    var panelBrowse=document.getElementById('picker-panel-browse'),panelUpload=document.getElementById('picker-panel-upload');
    var gridContainer=document.getElementById('picker-grid-container'),grid=document.getElementById('picker-grid');
    var sidebarState=document.getElementById('sidebar-content-state'),indicator=document.getElementById('picker-loading-indicator');
    var loadMoreTrigger=document.getElementById('picker-load-more-trigger'),btnLoadMore=document.getElementById('picker-btn-load-more');
    var metaInfo=document.getElementById('picker-meta-info'),btnConfirm=document.getElementById('picker-btn-confirm');
    var searchInput=document.getElementById('picker-search'),filterType=document.getElementById('picker-filter-type');
    var filterSort=document.getElementById('picker-filter-sort'),btnRefresh=document.getElementById('picker-btn-refresh');
    var btnViewGrid=document.getElementById('picker-view-grid'),btnViewList=document.getElementById('picker-view-list');
    var mediaItemsMap=new Map(),pickerSelectedItem=null,pickerLastUploadedItem=null,pickerMultiMode=false,pickerMultiSet=new Map();
    var pickerCurrentPage=1,pickerLastPage=1,pickerCurrentFolderId='';
    var btnBack=document.getElementById('picker-btn-back');
    var pickerFolderHistory=[],pickerFoldersArray=[],pickerBreadcrumbsArray=[];
    function updateBackBtn(){if(!btnBack)return;var inside=!!pickerCurrentFolderId||pickerFolderHistory.length>0;if(inside){btnBack.classList.remove('d-none');}else{btnBack.classList.add('d-none');}}
    if(btnBack){btnBack.addEventListener('click',function(){if(pickerFolderHistory.length>0){pickerCurrentFolderId=pickerFolderHistory.pop();}else{pickerCurrentFolderId='';}updateBackBtn();loadPickerData(1);});}
    var isFetching=false,isUploading=false,isListView=false,currentAbortController=null,USE_INFINITE_SCROLL=true;
    function switchTab(a){var b=a==='browse';tabBrowse.className='nav-link '+(b?'active':'');tabUpload.className='nav-link '+(!b?'active':'');tabBrowse.setAttribute('aria-selected',b);tabUpload.setAttribute('aria-selected',!b);if(b){panelBrowse.classList.remove('d-none');panelBrowse.classList.add('d-flex');panelUpload.classList.add('d-none');}else{panelBrowse.classList.add('d-none');panelUpload.classList.remove('d-none');panelUpload.classList.add('d-flex');}}
    tabBrowse.addEventListener('click',function(){switchTab('browse');});tabUpload.addEventListener('click',function(){switchTab('upload');});
    function setViewMode(m){var fg=document.getElementById('picker-folder-grid');if(m==='list'){isListView=true;btnViewList.classList.add('active');btnViewGrid.classList.remove('active');grid.className='d-flex flex-column gap-2';if(fg)fg.className='d-flex flex-column gap-2';}else{isListView=false;btnViewGrid.classList.add('active');btnViewList.classList.remove('active');grid.className='row g-2';if(fg)fg.className='row g-2';}loadPickerData(1);}
    btnViewGrid.addEventListener('click',function(){setViewMode('grid');});btnViewList.addEventListener('click',function(){setViewMode('list');});
    function itemThumb(item){return (item.conversions&&item.conversions.thumb)?item.conversions.thumb:(item.url||item.original_url||'');}
    function createGridItemEl(item){mediaItemsMap.set(item.id,item);var el=document.createElement('div');el.className=isListView?'picker-item picker-item--list position-relative d-flex flex-row align-items-center':'picker-item picker-item--grid position-relative d-flex flex-column';el.dataset.id=item.id;el.tabIndex=0;el.setAttribute('role','button');el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}});var isImg=item.mime_type&&item.mime_type.startsWith('image/'),url=itemThumb(item);var ic=document.createElement('div');if(isListView){ic.className='picker-item-thumb rounded overflow-hidden d-flex align-items-center justify-content-center shrink-0';}else{ic.className='picker-item-thumb w-100 position-relative overflow-hidden shrink-0 d-flex align-items-center justify-content-center';}if(isImg&&url){var img=document.createElement('img');img.src=url;img.draggable=false;img.className=isListView?'w-100 h-100 object-fit-cover':'position-absolute top-0 start-0 w-100 h-100 object-fit-cover';ic.appendChild(img);}else{ic.innerHTML='<svg width="'+(isListView?24:40)+'" height="'+(isListView?24:40)+'" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="text-body-secondary"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg>';}el.appendChild(ic);var chk=document.createElement('div');chk.className='picker-check position-absolute top-0 end-0 m-1 d-none align-items-center justify-content-center';chk.innerHTML='<svg width="12" height="12" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7"/></svg>';el.appendChild(chk);if(pickerMultiMode&&pickerMultiSet.has(item.id)){el.classList.add('picker-item-selected');chk.classList.remove('d-none');chk.classList.add('d-flex');}if(isListView){var info=document.createElement('div');info.className='flex-grow-1 px-2';info.innerHTML='<p class="fw-semibold small text-truncate mb-0">'+(item.file_name||'')+'</p><p class="small text-body-secondary mb-0" style="font-size:0.7rem;">'+(item.human_readable_size||'')+'</p>';el.appendChild(info);}return el;}
var sidebarEmpty=document.getElementById('sidebar-empty-state');function updateSidebarInfo(item){if(!item){sidebarState.classList.add('d-none');sidebarState.classList.remove('d-flex');if(sidebarEmpty){sidebarEmpty.classList.remove('d-none');sidebarEmpty.classList.add('d-flex');}return;}sidebarState.classList.remove('d-none');sidebarState.classList.add('d-flex');if(sidebarEmpty){sidebarEmpty.classList.add('d-none');sidebarEmpty.classList.remove('d-flex');}var pi=document.getElementById('sidebar-preview-img'),po=document.getElementById('sidebar-preview-icon');var isImg=item.mime_type&&item.mime_type.startsWith('image/'),url=itemThumb(item);if(isImg&&url){pi.src=url;pi.classList.remove('d-none');po.classList.add('d-none');}else{pi.classList.add('d-none');po.classList.remove('d-none');}document.getElementById('sidebar-info-name').textContent=item.file_name||'';document.getElementById('sidebar-info-date').textContent=item.formatted_date||item.created_at||'';document.getElementById('sidebar-info-size').textContent=item.human_readable_size||'';document.getElementById('sidebar-info-mime').textContent=item.extension||'';document.getElementById('sidebar-info-url').value=item.original_url||item.url||'';}    
        function renderPickerBreadcrumbs(){var bc=document.getElementById('picker-folder-breadcrumb');bc.innerHTML='';var r=document.createElement('a');r.href='#';r.className='text-decoration-none text-primary fw-medium';r.textContent='Tất cả ảnh';r.addEventListener('click',function(e){e.preventDefault();pickerCurrentFolderId='';pickerFolderHistory=[];updateBackBtn();loadPickerData(1);});bc.appendChild(r);pickerBreadcrumbsArray.forEach(function(f){var s=document.createElement('span');s.className='text-body-secondary mx-1';s.textContent='/';bc.appendChild(s);var a=document.createElement('a');a.href='#';a.className='text-decoration-none text-primary fw-medium';a.textContent=f.name;a.addEventListener('click',function(e){e.preventDefault();var idx=pickerBreadcrumbsArray.findIndex(function(bb){return bb.uuid===f.uuid;});if(idx>=0){var ancestors=pickerBreadcrumbsArray.slice(0,idx).map(function(bb){return bb.uuid;});pickerFolderHistory=[''].concat(ancestors);}else{pickerFolderHistory=[];}pickerCurrentFolderId=f.uuid;updateBackBtn();loadPickerData(1);});bc.appendChild(a);});}
    function renderPickerFolders(){var fs=document.getElementById('picker-folder-section'),fg=document.getElementById('picker-folder-grid');fg.innerHTML='';if(!pickerFoldersArray.length){fs.classList.add('d-none');return;}fs.classList.remove('d-none');pickerFoldersArray.forEach(function(folder){var el=document.createElement('div');el.className='picker-folder-card folder-item position-relative bg-body border rounded overflow-hidden shadow-sm d-flex flex-column justify-content-between';el.style.cursor='pointer';if(isListView){el.classList.add('w-100','flex-row','align-items-center','p-1');el.style.height='4rem';}else{el.classList.add('aspect-square');el.style.width='12.5%';}var ic=document.createElement('div');ic.className=isListView?'shrink-0 bg-primary bg-opacity-10 rounded d-flex align-items-center justify-content-center text-primary':'w-100 h-100 flex-grow-1 bg-primary bg-opacity-10 d-flex flex-column align-items-center justify-content-center text-primary';if(isListView)ic.style.cssText='width:3rem;height:3rem;';ic.innerHTML='<svg width="'+(isListView?24:40)+'" height="'+(isListView?24:40)+'" fill="currentColor" viewBox="0 0 20 20"><path d="M2 6a2 2 0 012-2h5l2 2h5a2 2 0 012 2v6a2 2 0 01-2 2H4a2 2 0 01-2-2V6z"/></svg>';if(!isListView){var t=document.createElement('div');t.className='w-100 px-2 text-center small fw-semibold text-truncate position-absolute bottom-0 mb-2';t.textContent=folder.name;ic.appendChild(t);}el.appendChild(ic);if(isListView){var td=document.createElement('div');td.className='flex-grow-1 px-3';td.innerHTML='<p class="fw-semibold small text-truncate mb-0">'+folder.name+'</p>';el.appendChild(td);}el.addEventListener('click',function(){if(pickerCurrentFolderId!==folder.uuid){pickerFolderHistory.push(pickerCurrentFolderId);pickerCurrentFolderId=folder.uuid;updateBackBtn();loadPickerData(1);}});fg.appendChild(el);});}
    async function loadPickerData(page,append){if(isFetching)return;if(currentAbortController)currentAbortController.abort();currentAbortController=new AbortController();isFetching=true;pickerCurrentPage=page||1;if(!append){grid.innerHTML='';mediaItemsMap.clear();pickerSelectedItem=null;updateSidebarInfo(null);btnConfirm.disabled=pickerMultiMode?(pickerMultiSet.size===0):true;if(pickerMultiMode&&pickerMultiSet.size>0)btnConfirm.textContent='Chọn '+pickerMultiSet.size+' ảnh';metaInfo.textContent='';}indicator.classList.remove('d-none');loadMoreTrigger.classList.add('d-none');var params=new URLSearchParams({page:pickerCurrentPage,keyword:searchInput.value.trim(),type:filterType.value,sort:filterSort.value});if(pickerCurrentFolderId)params.append('folder',pickerCurrentFolderId);try{var response=await fetch('/admin/media?'+params.toString(),{headers:{'Accept':'application/json','X-Requested-With':'XMLHttpRequest'},signal:currentAbortController.signal});if(!response.ok)throw new Error('API Error');var res=await response.json();var items=res.media?res.media.data:(res.data||[]);var meta=res.media?res.media:(res.meta||res);if(!append){if(res.folders)pickerFoldersArray=res.folders;if(res.breadcrumbs)pickerBreadcrumbsArray=res.breadcrumbs;renderPickerBreadcrumbs();renderPickerFolders();}pickerLastPage=meta.last_page||1;if(!append&&items.length===0&&!pickerFoldersArray.length){grid.innerHTML='<div class="col-12 py-5 text-center text-body-secondary small">Không tìm thấy tập tin nào.</div>';}else{items.forEach(function(item){grid.appendChild(createGridItemEl(item));});if(!append){var currentId=modal.dataset.currentId;if(currentId){for(var ci=0;ci<items.length;ci++){if(items[ci].uuid===currentId){var preEl=findItemEl(items[ci]);if(preEl)preEl.scrollIntoView({block:'nearest'});selectItem(items[ci],preEl);break;}}}}}indicator.classList.add('d-none');metaInfo.textContent=meta.total?'Đã tải '+grid.children.length+' / '+meta.total+' file':'';if(pickerCurrentPage<pickerLastPage){loadMoreTrigger.classList.remove('d-none');if(USE_INFINITE_SCROLL)setupInfiniteScrollObserver();}}catch(error){if(error.name!=='AbortError'){console.error('Lỗi media:',error);indicator.classList.add('d-none');if(!append)grid.innerHTML='<div class="col-12 text-danger text-center small py-5">Đã xảy ra lỗi khi tải dữ liệu.</div>';}}finally{isFetching=false;}}
    var searchTimer;searchInput.addEventListener('input',function(){clearTimeout(searchTimer);searchTimer=setTimeout(function(){loadPickerData(1);},400);});
    filterType.addEventListener('change',function(){loadPickerData(1);});filterSort.addEventListener('change',function(){loadPickerData(1);});
    btnRefresh.addEventListener('click',function(){loadPickerData(1);});
    btnLoadMore.addEventListener('click',function(){if(!isFetching&&pickerCurrentPage<pickerLastPage)loadPickerData(pickerCurrentPage+1,true);});
    var intersectionObserver=null;function setupInfiniteScrollObserver(){if(intersectionObserver)intersectionObserver.disconnect();intersectionObserver=new IntersectionObserver(function(entries){if(entries[0].isIntersecting&&!isFetching&&pickerCurrentPage<pickerLastPage)loadPickerData(pickerCurrentPage+1,true);},{root:gridContainer,rootMargin:'150px'});intersectionObserver.observe(loadMoreTrigger);}
    function clearPickerSelection(){grid.querySelectorAll('.picker-item').forEach(function(el){el.classList.remove('picker-item-selected');var c=el.querySelector('.picker-check');if(c){c.classList.add('d-none');c.classList.remove('d-flex');}});}
    function deselectItem(itemEl){itemEl.classList.remove('picker-item-selected');var chk=itemEl.querySelector('.picker-check');if(chk){chk.classList.add('d-none');chk.classList.remove('d-flex');}if(pickerMultiMode){pickerMultiSet.delete(Number(itemEl.dataset.id));updateMultiConfirmBtn();}else{pickerSelectedItem=null;updateSidebarInfo(null);btnConfirm.disabled=true;}}
    function selectItem(item,itemEl){if(!item)return;if(pickerMultiMode){pickerMultiSet.set(item.id,item);if(itemEl){itemEl.classList.add('picker-item-selected');var check=itemEl.querySelector('.picker-check');if(check){check.classList.remove('d-none');check.classList.add('d-flex');}}updateMultiConfirmBtn();updateSidebarInfo(item);return;}clearPickerSelection();if(itemEl){itemEl.classList.add('picker-item-selected');var check=itemEl.querySelector('.picker-check');if(check){check.classList.remove('d-none');check.classList.add('d-flex');}}pickerSelectedItem=item;btnConfirm.disabled=false;updateSidebarInfo(item);}
    function updateMultiConfirmBtn(){var n=pickerMultiSet.size;btnConfirm.disabled=(n===0);btnConfirm.textContent=n>0?('Chọn '+n+' ảnh'):'Xác nhận chọn';}
    function findItemEl(item){return grid.querySelector('.picker-item[data-id="'+String(item.id)+'"]')||null;}
    grid.addEventListener('click',function(e){var itemEl=e.target.closest('.picker-item');if(!itemEl)return;if(itemEl.classList.contains('picker-item-selected')){deselectItem(itemEl);return;}var item=mediaItemsMap.get(Number(itemEl.dataset.id));selectItem(item,itemEl);});
    var dropzone=document.getElementById('picker-dropzone'),fileInput=document.getElementById('picker-file-input'),resultEl=document.getElementById('picker-upload-result'),overlay=document.getElementById('picker-upload-overlay'),progBar=document.getElementById('picker-progress-bar'),progPct=document.getElementById('picker-progress-pct'),progName=document.getElementById('picker-progress-name');
    function handleUpload(file,isFromGrid){if(!file||isUploading)return;if(file.size>10*1024*1024){if(typeof AdminUI!=='undefined')AdminUI.notify('error','File vượt quá 10MB.');fileInput.value='';return;}isUploading=true;if(!isFromGrid){overlay.classList.remove('d-none');overlay.classList.add('d-flex');resultEl.classList.add('d-none');fileInput.disabled=true;}progName.textContent=file.name;progBar.style.width='0%';progPct.textContent='0%';var formData=new FormData();formData.append('file',file);formData.append('collection_name','default');if(pickerCurrentFolderId)formData.append('folder_id',pickerCurrentFolderId);var csrfToken=document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';var xhr=new XMLHttpRequest();xhr.open('POST','/admin/media',true);xhr.setRequestHeader('X-CSRF-TOKEN',csrfToken);xhr.setRequestHeader('Accept','application/json');xhr.upload.addEventListener('progress',function(e){if(e.lengthComputable){var pct=Math.round((e.loaded/e.total)*100);progBar.style.width=pct+'%';progPct.textContent=pct+'%';}});xhr.onload=function(){isUploading=false;if(!isFromGrid){overlay.classList.add('d-none');overlay.classList.remove('d-flex');fileInput.disabled=false;}if(xhr.status>=200&&xhr.status<300){var res=JSON.parse(xhr.responseText);pickerLastUploadedItem=res.data||res;if(!isFromGrid){resultEl.classList.remove('d-none');var thumb=document.getElementById('picker-upload-thumb');var isImg=pickerLastUploadedItem.mime_type&&pickerLastUploadedItem.mime_type.startsWith('image/');var url=itemThumb(pickerLastUploadedItem);if(isImg&&url){thumb.src=url;thumb.classList.remove('d-none');}else{thumb.src='';thumb.classList.add('d-none');}document.getElementById('picker-upload-filename').textContent=pickerLastUploadedItem.file_name||'';}if(typeof AdminUI!=='undefined')AdminUI.notify('success','Tải lên thành công!');switchTab('browse');loadPickerData(1);}else{var msg='Lỗi khi tải lên.';try{var errRes=JSON.parse(xhr.responseText);msg=errRes.message||(errRes.errors?Object.values(errRes.errors)[0]:msg);}catch(pe){}if(typeof AdminUI!=='undefined')AdminUI.notify('error',msg);}};xhr.onerror=function(){isUploading=false;if(!isFromGrid){overlay.classList.add('d-none');overlay.classList.remove('d-flex');fileInput.disabled=false;}if(typeof AdminUI!=='undefined')AdminUI.notify('error','Lỗi kết nối.');};xhr.send(formData);}
    fileInput.addEventListener('change',function(){if(fileInput.files&&fileInput.files[0])handleUpload(fileInput.files[0]);});
    dropzone.addEventListener('dragover',function(e){e.preventDefault();dropzone.classList.add('picker-dropzone-active');});dropzone.addEventListener('dragleave',function(e){e.preventDefault();dropzone.classList.remove('picker-dropzone-active');});dropzone.addEventListener('drop',function(e){e.preventDefault();dropzone.classList.remove('picker-dropzone-active');if(e.dataTransfer.files&&e.dataTransfer.files.length>0)handleUpload(e.dataTransfer.files[0]);});
    var dragCounter=0,gridDropOverlay=document.getElementById('picker-grid-drop-overlay');
    gridContainer.addEventListener('dragenter',function(e){e.preventDefault();dragCounter++;gridDropOverlay.classList.remove('d-none');gridDropOverlay.classList.add('d-flex');});gridContainer.addEventListener('dragleave',function(e){e.preventDefault();dragCounter--;if(dragCounter===0){gridDropOverlay.classList.add('d-none');gridDropOverlay.classList.remove('d-flex');}});gridContainer.addEventListener('dragover',function(e){e.preventDefault();});gridContainer.addEventListener('drop',function(e){e.preventDefault();dragCounter=0;gridDropOverlay.classList.add('d-none');gridDropOverlay.classList.remove('d-flex');if(e.dataTransfer.files&&e.dataTransfer.files.length>0)handleUpload(e.dataTransfer.files[0],true);});
    document.getElementById('sidebar-btn-delete').addEventListener('click',function(evt){if(!pickerSelectedItem)return;var btn=evt.currentTarget;function doDelete(){btn.disabled=true;btn.textContent='Đang xóa...';var csrfToken=document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';fetch('/admin/media/'+pickerSelectedItem.uuid,{method:'DELETE',headers:{'X-CSRF-TOKEN':csrfToken,'Accept':'application/json'}}).then(function(res){if(!res.ok)throw new Error('Xóa thất bại');var el=document.querySelector('.picker-item[data-id="'+pickerSelectedItem.id+'"]');if(el)el.remove();pickerSelectedItem=null;updateSidebarInfo(null);btnConfirm.disabled=true;if(typeof AdminUI!=='undefined')AdminUI.notify('success','Đã xóa file.');}).catch(function(){if(typeof AdminUI!=='undefined'){AdminUI.alert('Lỗi','Không thể xóa file.','error');}else{alert('Lỗi khi xóa file.');}}).finally(function(){btn.disabled=false;btn.textContent='Xóa vĩnh viễn';});}if(typeof AdminUI!=='undefined'){AdminUI.confirm({title:'Xóa file?',text:'Bạn có chắc chắn muốn xóa file này vĩnh viễn?',confirmText:'Xóa',cancelText:'Hủy'},doDelete);}else{if(confirm('Bạn có chắc chắn muốn xóa file này vĩnh viễn?'))doDelete();}});    
    btnConfirm.addEventListener('click',function(){if(pickerMultiMode){if(pickerMultiSet.size===0)return;dispatchMultiSelectedEvent();return;}if(!pickerSelectedItem)return;dispatchSelectedEvent(pickerSelectedItem);});
    document.getElementById('picker-btn-use-uploaded').addEventListener('click',function(){if(!pickerLastUploadedItem)return;dispatchSelectedEvent(pickerLastUploadedItem);});
    function dispatchSelectedEvent(item){var targetId=modal.dataset.activeTarget;if(targetId){var targetEl=document.getElementById(targetId);if(targetEl)targetEl.dispatchEvent(new CustomEvent('media-picker-selected',{detail:item,bubbles:true}));}resultEl.classList.add('d-none');pickerLastUploadedItem=null;closeModal('global-media-picker');}
    function dispatchMultiSelectedEvent(){var targetId=modal.dataset.activeTarget;if(targetId){var targetEl=document.getElementById(targetId);if(targetEl){var items=Array.from(pickerMultiSet.values());targetEl.dispatchEvent(new CustomEvent('media-picker-multi-selected',{detail:{items:items},bubbles:true}));}}resultEl.classList.add('d-none');pickerLastUploadedItem=null;closeModal('global-media-picker');}
    document.addEventListener('global-media-picker-open',function(){pickerSelectedItem=null;pickerLastUploadedItem=null;pickerMultiMode=(modal.dataset.multi==='1');pickerMultiSet=new Map();btnConfirm.disabled=true;if(pickerMultiMode){btnConfirm.textContent='Xác nhận chọn';delete modal.dataset.currentId;}pickerCurrentFolderId='';pickerFolderHistory=[];updateBackBtn();resultEl.classList.add('d-none');switchTab('browse');loadPickerData(1);});
});
</script>
@endPushOnce